-- create database SalesmanTab;
-- create table salesman(
-- salesman_id int not null primary key,
-- salesman_name  varchar(30) not null,
-- city varchar(30) not null,
-- commission float not null
-- );
-- insert into salesman(salesman_id,salesman_name,city,commission)
-- values
-- (5001,"James Hoog","New York",0.15),
-- (5002,"Nail","Paris",0.13),
-- (5005,"Pit Alex","London",0.11),
-- (5006,"Mc Lyon","Paris",0.14),
-- (5007,"Paul Adam","Rome",0.13),
-- (5003,"Lauson","San Jose",0.12);
-- create table customerTab(
-- customer_id int not null primary key,
-- cust_name varchar(30) not null,
-- city varchar(30) not null,
-- grade int not null,
-- salesman_id int not null
-- );
